import Head from "next/head";
import dynamic from "next/dynamic";

const HeroBanner = dynamic(() => import("@/components/rendering/heroBanner"));

export default function HomePage() {
  return (
    <>
      <Head>
        <title>WaoSim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta property="og:image" content="/path/to/your/thumbnail.jpg" /> */}
        <link rel="icon" href="/faviconIcon.svg" />
      </Head>
      <main>
        <HeroBanner />
      </main>
    </>
  );
}

// export async function getServerSideProps({ req }: any) {
//   const { isError, response } = await getAllCountryRegion();

//   return {
//     props: {
//       response: response?.data,
//     },
//   };
// }
