import Head from "next/head";

export default function TermsConditionsPage({ response }: any) {
  return (
    <>
      <Head>
        <title>WaoSim | Terms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconIcon.svg" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            height: "50vh",
            width: "100%",
            backgroundColor: "#FFF0ED",
          }}
        >
          <h1> Terms & Conditions</h1>
        </div>
      </main>
    </>
  );
}

// export async function getServerSideProps({ req }: any) {
//   const { isError, response } = await getAllCountryRegion();

//   return {
//     props: {
//       response: response?.data,
//     },
//   };
// }
